### ISSUE TITLE
Site Offline

### ISSUE THREAD

**Issue by jwangaard** [Four51/CustomSolutions#55]
A customer asked:  "I have a site that is seasonal.  Can you develop a custom solution that would enable\disable the site?  When the site is disabled, I would like the ability to customize a message to the customer."

**Comment by abishop451** [comment]
We have created a Custom Solution for this, which you can easily add to your site when you need it.  It is called the Sitedown Splash page.  Details about the Custom Solution can be found on our demo site [here](https://volition.four51ordercloud.com/store/product/SitedownSplashPage).  The code and instructions to implement can be found on GitHub [here](https://github.com/Four51/CustomSolutions/tree/master/Sitedown%20Splash%20Page).
